### ISSUE TITLE
Cache APIResponse

### ISSUE THREAD

**Issue by stefan2904** [michiwend/wp_spacestatus#1]
**Problem:**

Multiple shortcode usages on one page lead to multiple calls to the SpaceAPI endpoint. This is not necessary. 

**Suggested solution:**

Cache SpaceAPI response, for example by implementing `APIResponse` as singleton.

**Comment by PeterTheOne** [comment]
Maybe use [set_transient](https://codex.wordpress.org/Function_Reference/set_transient), see: http://www.paulund.co.uk/cache-data-with-wordpress .

How long should it be cached? 10 minutes?

**Comment by michiwend** [comment]
@PeterTheOne Hmm, not sure if caching really makes sense for a live status. More important is the re-usage of the API response for multiple shortcodes. But if you feel lucky, you can implement it with a settings option to change the time respectively disable it?

thx for contributing :thumbsup:

**Comment by PeterTheOne** [comment]
@michiwend True, doesn't really make sense to use caching in this use case.

you're welcome. :)

**Comment by PeterTheOne** [comment]
We could use set_transient to respect the cache value of the spaceapi, see: http://spaceapi.net/documentation#documentation-ref-13-root-cache .
